fix the addon installation script
NOTE This fix still results in a broken workshopper. The guides pod fails to start with this log output: 

* Version 3.10.0 (ruby 2.4.1-p111), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
NoMethodError: undefined method `keys' for nil:NilClass
  /workshopper/lib/workshopper/workshop.rb:62:in `resolve'
  /workshopper/lib/workshopper/workshop.rb:53:in `setup'
  /workshopper/lib/workshopper/workshop.rb:12:in `initialize'
  /workshopper/lib/workshopper/deployment.rb:25:in `new'
  /workshopper/lib/workshopper/deployment.rb:25:in `add'
  /workshopper/lib/workshopper/deployment.rb:11:in `block in initialize'
  /workshopper/lib/workshopper/deployment.rb:10:in `each'
  /workshopper/lib/workshopper/deployment.rb:10:in `initialize'
  /workshopper/lib/workshopper/webapp.rb:10:in `new'
  /workshopper/lib/workshopper/webapp.rb:10:in `<class:Webapp>'
  /workshopper/lib/workshopper/webapp.rb:5:in `<module:Workshopper>'
  /workshopper/lib/workshopper/webapp.rb:4:in `<top (required)>'
  /workshopper/lib/workshopper.rb:13:in `require'
  /workshopper/lib/workshopper.rb:13:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:314:in `load_rackup'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:243:in `app'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/runner.rb:138:in `load_and_bind'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/single.rb:87:in `run'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
  /workshopper/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
  /workshopper/vendor/bundle/ruby/2.4.0/bin/puma:22:in `load'
  /workshopper/vendor/bundle/ruby/2.4.0/bin/puma:22:in `<top (required)>'
! Unable to load application: NoMethodError: undefined method `keys' for nil:NilClass
bundler: failed to load command: puma (/workshopper/vendor/bundle/ruby/2.4.0/bin/puma)